export default {
    OB1 : require ('../assets/OnBoardingImage/obs1.png'),
    OB2 : require ('../assets/OnBoardingImage/obs2.png'),
    OB3 : require ('../assets/OnBoardingImage/obs3.png'),
    OB4 : require ('../assets/OnBoardingImage/obs4.png'),
    OB5 : require ('../assets/OnBoardingImage/obs5.png'),
    OB6 : require ('../assets/OnBoardingImage/obs6.png'),
    ICON : require ('../assets/Icons/logo1.png'),
    ICON2 : require ('../assets/Icons/logo_text.png'),
    TEXTLOGO : require ('../assets/Icons/textlogo.png'),
    icHome : require ('../assets/Icons/home.png'),
    icProfile : require ('../assets/Icons/profile.png'),
    icInfo : require ('../assets/Icons/info.png'),
    icHisto : require ('../assets/Icons/history.png'),
    icSpeak : require ('../assets/Icons/speak.png'),
    icEdit : require ('../assets/Icons/edit.png'),
    icDet : require ('../assets/Icons/details.png'),
    icHelp : require ('../assets/Icons/help.png'),
    icMan : require ('../assets/Icons/manage.png'),
}